apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-sitepush-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "SitePush Management"
    rbac.authorization.halo.run/display-name: "Site Push View"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:sitepush:view"]
rules:
  - apiGroups: [ "sitepush.halo.run" ]
    resources: [ "pushLogs" , "pushUniques" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-sitepush-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "SitePush Management"
    rbac.authorization.halo.run/display-name: "Site Push Management"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:sitepush:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-sitepush-view"]
rules:
  - apiGroups: [ "sitepush.halo.run" ]
    resources: [ "pushLogs" , "pushUniques" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]