apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-sitepush-settings
spec:
  forms:
    - group: basic
      label: Basic Settings
      formSchema:
        - $formkit: radio
          name: enable
          id: enable
          key: enable
          label: Whether to enable site indexing push
          help: After disabling, all site pushes on the right will not take effect
          value: false
          options:
            - label: Enable
              value: true
            - label: Disable
              value: false

        - $formkit: text
          if: $get(enable).value
          name: siteUrl
          label: Site URL
          placeholder: Please enter the site URL
          help: Required after enabling, format: http(s)://(www.)example.com, no slash at the end, cannot push if not filled

        - $formkit: number
          if: $get(enable).value
          name: retryInterval
          label: Retry interval time (minutes)
          help: Default is 360 minutes, set to 0 means no retry
          value: 360

        - $formkit: number
          if: $get(enable).value
          name: cleanOldLogDataDays
          label: Clean old push log data before specified days every 1 hour
          help: Only clean when value > 0, unit (days)
          value: 0
        - $formkit: number
          if: $get(enable).value
          name: cleanOldUniqueDataDays
          label: Clean old push key data before specified days every 1 hour
          help: Only clean when value > 0, unit (days), cleaned URLs will trigger push again later
          value: 0

    - group: baidu
      label: Baidu Indexing Push
      formSchema:
        - $formkit: radio
          name: baiduEnableTagVerification
          id: baiduEnableTagVerification
          key: baiduEnableTagVerification
          label: Whether to enable tag verification
          value: true
          options:
            - label: Yes
              value: true
            - label: No
              value: false

        - $formkit: text
          if: $get(baiduEnableTagVerification).value
          name: siteVerification
          label: Baidu site verification (verification code)
          placeholder: Format: codeva-xxxxxxx
          help: Application address: https://ziyuan.baidu.com/site/siteadd, website verification uses HTML tag verification, the content in the code is the verification code to fill in, takes effect 1 minute after modification

        - $formkit: radio
          name: baiduEnable
          id: baiduEnable
          key: baiduEnable




